# Generated by Django 5.0.6 on 2024-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_petrolstation_category_alter_fueltype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrolstation',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='petrolstation',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='petrolstation',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
